export const TOGGLE_MODAL_ON = "TOGGLE_MODAL_ON";
export const TOGGLE_MODAL_OFF = "TOGGLE_MODAL_OFF";
export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR";
export const TOGGLE_LOGIN = "TOGGLE_LOGIN";
export const SEARCH_AREA = "SEARCH_AREA";
